Revert "sched/fair: Add policy for restricting prefer_spread to newly idle balance"
* Fix build error
../kernel/sched/fair.c:4011:44: error: too many arguments to function call, expected single argument 'cpu', have 2 arguments
        if (prefer_spread_on_idle(*best_idle_cpu, false))
            ~~~~~~~~~~~~~~~~~~~~~                 ^~~~~
../kernel/sched/walt.h:472:20: note: 'prefer_spread_on_idle' declared here
static inline bool prefer_spread_on_idle(int cpu)
                   ^
This reverts commit f1771866469cebed64521e7b9941e5cf9e255d51.

Signed-off-by: Diaz1401 <reagor8161@outlook.com>